plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/gj/다리 클로드코드/상세페이지"
publishOrigin = "default"
base = "/Users/gj/다리 클로드코드/상세페이지"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]